### ISSUE TITLE
White render with cmd-drawMesh

### ISSUE THREAD

**Issue by kefon** [Cyanilux/URP_BlitRenderFeature#11]
Hey. First, awesome work! I'm trying to setup your WatercolourShaders with an occulus quest 2, and because of XR, I switched the blitRenderFeature to the cmd-drawMesh version.

Without the cmd-drawMesh version, 
- if I play in the editor (processed by the computer and sent to the headset for display), everything is working fine.
- if I build and play (processed directly by android on the headset), I'm having huge weird color lines over the render in the headset (but I guess it's because of the incompatibility with XR)

With the cmd-drawMesh version, 
- In both case, I'm having only the "outlines" rendered (the ones created by the edge detection in the shadergraph), but everything else is white (sure the effect is cool, but not what I expect ;) ). I'm using the BlitDirectly shader in the "always include" graphic setting, and I can't understand why I'm having this issue...

Any idea how to solve this issue?
Thanks in advance!

![Screenshot_1](https://user-images.githubusercontent.com/5464064/161574513-5632c70c-8599-4125-b8f5-0a5958cb1ff7.jpg)

**Comment by Cyanilux** [comment]
Hey! The cmd-DrawMesh version works a little differently to obtain the source texture. It's still passed into the `_MainTex` reference, but now must be **global** (aka **not** "exposed" in Shader Graph, under the Node Settings for that property)

But in order to work correctly with Single Pass Instanced rendering, there's also a `Sample Main Texture` subgraph provided (I added it a few weeks ago, along with fixing some other issues). So should be able to remove the texture property and replace the current `Sample Texture 2D` node with that subgraph instead.

Note : That might be Unity 2021.2+ only too, since I'm using the new custom binding & `Branch On Input Connection` node. 
Not sure what happens if you attempt to load that in older versions, might just error.
If you do need it for older versions, and assuming the rest of the feature still works, could probably use a `Custom Function` node with the `FullscreenHelperFunctions.hlsl` file & `SampleMainTexture` function.

**Comment by kefon** [comment]
Thanks a lot for the (incridibly fast) help! It worked. I used the subgraph with `FullscreenHelperFunctions.hlsl` file and `SampleMainTexture`, and removed the exposed `_MainTex` in the shader graph as you described. I also modified the `FullscreenHelperFunctions.hlsl` file a bit because I'm on 2020.3, and yes the `Branch On Input Connection` node is not available so I removed it (not a problem since the project is intended for single pass VR). Well, thanks again for your help, I learned a lot while diving into it!
