### ISSUE TITLE
Unity 2023.2.20f1

### ISSUE THREAD

**Issue by NotThisJin** [Cyanilux/URP_BlitRenderFeature#21]
Seems that this doesnt work for this version of unity.
![image](https://github.com/Cyanilux/URP_BlitRenderFeature/assets/51182170/e3f0313c-c6ec-4175-86b2-d7974f3d3713)

**Comment by Cyanilux** [comment]
Since you closed this you may have figured this out, but to clarify if others come across this - there are branches for various versions.
- Master one currently is for up to 2021.3 and will likely stay like this. It *should* support older versions but there's a 2019-2021.1 branch just in case.
- There's a 2022.1 branch that uses RTHandles & Blitter API. That will likely work in higher versions but for 2022.2+ you can also blit to camera targets using the **Fullscreen Pass Renderer Feature** that URP now provides. You'd only need this feature for using custom targets.
- Also 2023.3 / Unity 6 should use the newer RenderGraph API. Should be able to find an example in [this forum thread](https://forum.unity.com/threads/introduction-of-render-graph-in-the-universal-render-pipeline-urp.1500833/) (Note that as of 2023.3.0a18, UseTextureFragment has been renamed to SetRenderAttachment and UseTextureFragmentDepth is SetRenderAttachmentDepth)
